/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.edunova.finalapp.view;

import hr.edunova.finalapp.controller.ControllingAnimalSpecies;
import hr.edunova.finalapp.util.ApplicationInfo;
import hr.edunova.finalapp.model.Animal;
import hr.edunova.finalapp.model.AnimalSpecies;
import hr.edunova.finalapp.util.AppException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author Dalibor
 */
public class WindowAnimals extends javax.swing.JFrame {
    private ControllingAnimalSpecies controller;
    /**
     * Creates new form Animals
     */
    public WindowAnimals() {
        initComponents();
        settings();
        controller = new ControllingAnimalSpecies();
        loadList();
    }
    
    private void settings() {
        setTitle(ApplicationInfo.getTitle("Animals"));
    }

    private void loadList() {
        DefaultListModel<AnimalSpecies> m = new DefaultListModel<>();        
        controller.read().forEach(s->{
            m.addElement(s);
            System.out.println(s);
        });        
        lstAnimalSpecies.setModel(m);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAnimalsLabel = new javax.swing.JLabel();
        lblAnimalsSearch = new javax.swing.JLabel();
        txtAnimalsSearch = new javax.swing.JTextField();
        btnAnimalsSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAnimalSpecies = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblAnimalsLabel.setBackground(new java.awt.Color(204, 204, 204));
        lblAnimalsLabel.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lblAnimalsLabel.setText("Animals window");
        lblAnimalsLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblAnimalsSearch.setText("Type name, species or ID");

        btnAnimalsSearch.setText("Search");

        jScrollPane1.setViewportView(lstAnimalSpecies);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAnimalsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(lblAnimalsSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAnimalsSearch))
                .addGap(33, 33, 33)
                .addComponent(btnAnimalsSearch)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblAnimalsLabel)
                .addGap(18, 18, 18)
                .addComponent(lblAnimalsSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnimalsSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnimalsSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 78, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(WindowAnimals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(WindowAnimals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(WindowAnimals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(WindowAnimals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new WindowAnimals().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnimalsSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnimalsLabel;
    private javax.swing.JLabel lblAnimalsSearch;
    private javax.swing.JList<AnimalSpecies> lstAnimalSpecies;
    private javax.swing.JTextField txtAnimalsSearch;
    // End of variables declaration//GEN-END:variables


}
